version: '3'

services:

  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - hadoop-namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    ports:
      - 9870:9870

  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - hadoop-datanode:/hadoop/dfs/data
    environment:
      - HARDWARE_PROVIDER=docker
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hadoop-namenode:8020
    ports:
      - 9864:9864

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    environment:
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:mysql://mysql/metastore
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionDriverName=com.mysql.jdbc.Driver
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionUserName=hive
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionPassword=hive
      - HIVE_CORE_CONF_datanucleus_autoCreateSchema=false
      - HIVE_SITE_CONF_hive_metastore_uris=thrift://hive-metastore:9083
    ports:
      - 10000:10000

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    environment:
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:mysql://mysql/metastore
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionDriverName=com.mysql.jdbc.Driver
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionUserName=hive
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionPassword=hive
      - HIVE_CORE_CONF_datanucleus_autoCreateSchema=false
    ports:
      - 9083:9083

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=metastore
      - MYSQL_USER=hive
      - MYSQL_PASSWORD=hive
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

volumes:
  hadoop-namenode:
  hadoop-datanode: